name: caase_app
description: App para el control de asistencias de grupos de trabajo.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  cloud_firestore: ^2.5.3
  firebase_database: ^8.0.0
  get: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mision.png

 